### ISSUE TITLE
Neco mi tam chybi :)

### ISSUE THREAD

**Issue by MicTech** [Dzoukr/Nagano98#1]
Ahoj Romane, 👋
po 25 letech tam ty emoce pořád jsou, když si to pouštim, tak mám husí kůži.

Toho Brandona bych trochu rozšířil, tam je zásadní to "pokud ne, jsme tam"

**Comment by Dzoukr** [comment]
Tak to tam za chvíli máš (až se to zbuildí) 😉

**Comment by Dzoukr** [comment]
Btw... zkoušel jsi kliknout na logo Nagana? 😉

**Comment by MicTech** [comment]
> Btw... zkoušel jsi kliknout na logo Nagana? 😉

@Dzoukr Nic to nedela 🤷‍♂️

**Comment by Dzoukr** [comment]
Už jsem to změnil - teď to není jako easter egg, ale hlášek je vidět víc (a ještě bude :))
